# Generated by Django 2.0.1 on 2018-01-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancingsite', '0003_projectbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
