# Generated by Django 2.0.1 on 2018-01-30 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancingsite', '0004_auto_20180130_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbid',
            name='bid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbid',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='freelancingsite.Project'),
        ),
    ]
